GET http://localhost:5000/plates
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImttZXJ5IiwiYWRtaW4iOnRydWUsImlhdCI6MTU5Mjc4MjY2NSwiZXhwIjoxNTkyNzg2MjY1fQ.r3CMSqtZ2yGZDgLcKIl__U4mjNDefyPZWdlhRpArKD0

###
DELETE http://localhost:5000/order/1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImttZXJ5IiwiYWRtaW4iOnRydWUsImlhdCI6MTU5Mjc4MjY2NSwiZXhwIjoxNTkyNzg2MjY1fQ.r3CMSqtZ2yGZDgLcKIl__U4mjNDefyPZWdlhRpArKD0

###
PUT http://localhost:5000/order/1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImttZXJ5IiwiYWRtaW4iOnRydWUsImlhdCI6MTU5Mjc4MjY2NSwiZXhwIjoxNTkyNzg2MjY1fQ.r3CMSqtZ2yGZDgLcKIl__U4mjNDefyPZWdlhRpArKD0
Content-Type: application/json

{   
    "status":"Preparing"
    # "status":"test"
}

###
POST http://localhost:5000/order
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImttZXJ5IiwiYWRtaW4iOnRydWUsImlhdCI6MTU5Mjc4MjY2NSwiZXhwIjoxNTkyNzg2MjY1fQ.r3CMSqtZ2yGZDgLcKIl__U4mjNDefyPZWdlhRpArKD0
Content-Type: application/json

{   
    "userId": 2,
    "description" : "salad 1"
}
###
GET http://localhost:5000/order/user/1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImttZXJ5IiwiYWRtaW4iOnRydWUsImlhdCI6MTU5Mjc4MjY2NSwiZXhwIjoxNTkyNzg2MjY1fQ.r3CMSqtZ2yGZDgLcKIl__U4mjNDefyPZWdlhRpArKD0

###
GET http://localhost:5000/order
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImttZXJ5IiwiYWRtaW4iOnRydWUsImlhdCI6MTU5Mjc4MjY2NSwiZXhwIjoxNTkyNzg2MjY1fQ.r3CMSqtZ2yGZDgLcKIl__U4mjNDefyPZWdlhRpArKD0

###
POST http://localhost:5000/order
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImttZXJ5IiwiYWRtaW4iOnRydWUsImlhdCI6MTU5Mjc4MjY2NSwiZXhwIjoxNTkyNzg2MjY1fQ.r3CMSqtZ2yGZDgLcKIl__U4mjNDefyPZWdlhRpArKD0
Content-Type: application/json

{   
    "userId": 1,
    "description" : "salad 1",
    "quantity": 2
}
###
GET http://localhost:5000/plates/1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImttZXJ5IiwiYWRtaW4iOnRydWUsImlhdCI6MTU5MTgzMjg2MywiZXhwIjoxNTkxODM2NDYzfQ.AMgY3xCBVj0TUU15L7bhkgcgODR8isiQxabP4v43t-8

###
PUT http://localhost:5000/plates/1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImttZXJ5IiwiYWRtaW4iOnRydWUsImlhdCI6MTU5MjE4MzY4MiwiZXhwIjoxNTkyMTg3MjgyfQ.v-3upZP0b9uPrydvLN0-cEGlunoPbd1i8QJGSfH7GW8
Content-Type: application/json

{
    "price": 200
}

###
DELETE http://localhost:5000/plates/2
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTU5Mjc4NTY1MiwiZXhwIjoxNTkyNzg5MjUyfQ.wwFXhMEJsUcAKHjoodvR6TnPnkLeK3SvkgdQhRA2JaM
Content-Type: application/json

###
DELETE http://localhost:5000/users/1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImttZXJ5IiwiYWRtaW4iOnRydWUsImlhdCI6MTU5MjMzODU3MiwiZXhwIjoxNTkyMzQyMTcyfQ.mmUjQoOZYSvkHy2s54QSksZgKjyrlxBlpeLmGFnjlwU
Content-Type: application/json


###
GET http://localhost:5000/users/1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTU5MjE4Njg5NSwiZXhwIjoxNTkyMTkwNDk1fQ.lCPAwcW7Lf-6ZZBPwBoEsJ7CrB1FEBP5dVW7jBN-rtM
Content-Type: application/json

###
PUT http://localhost:5000/users/1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTU5MjE4Njg5NSwiZXhwIjoxNTkyMTkwNDk1fQ.lCPAwcW7Lf-6ZZBPwBoEsJ7CrB1FEBP5dVW7jBN-rtM
Content-Type: application/json

{
    "name": "testUser",
    "adress": "FakeStreet 321"
    # "telephone": 222111333,
    # "mail": "mail1@mail.com",
    # "password": "test"
}

###
GET http://localhost:5000/plates/1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7fSwiaWF0IjoxNTg5ODk3Njc4fQ.C5pA0DXtSR4Zz_OxM_NLEzOXaHl2IwbSkrDiSE17e0w

###
GET http://localhost:5000/users/1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImttZXJ5IiwiYWRtaW4iOnRydWUsImlhdCI6MTU5MjE4Njk5MiwiZXhwIjoxNTkyMTkwNTkyfQ.gmlVsvVRBWGZ5dyVuEoG4a2cZXYZdu7sfaS7So-_WnY
Content-Type: application/json

###
POST http://localhost:5000/users
Content-Type: application/json

{
    # "nameUser": "user"
    "password": "test"
}

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "nameUser": "user",
    # "admin": false, 
    "adress": "Neverland",
    "telephone": 333111444,
    "mail": "mail1@mail.com",
    "password": "test"
}

###
POST http://localhost:5000/plates
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImttZXJ5IiwiYWRtaW4iOnRydWUsImlhdCI6MTU5Mjc4MjY2NSwiZXhwIjoxNTkyNzg2MjY1fQ.r3CMSqtZ2yGZDgLcKIl__U4mjNDefyPZWdlhRpArKD0
Content-Type: application/json

{
    "plate": "salad 1",
    "price": 75
}

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "nameUser": "kmery",
    "admin": true, 
    "adress": "Neverland",
    "telephone": 333111444,
    "mail": "mail1@mail.com",
    "password": "test"
}
###
GET http://localhost:5000/users
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImttZXJ5IiwiYWRtaW4iOnRydWUsImlhdCI6MTU5MjMzODU3MiwiZXhwIjoxNTkyMzQyMTcyfQ.mmUjQoOZYSvkHy2s54QSksZgKjyrlxBlpeLmGFnjlwU
Content-Type: application/json


###
POST http://localhost:5000/plates
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImttZXJ5IiwiYWRtaW4iOnRydWUsImlhdCI6MTU5MjcxMzYwOCwiZXhwIjoxNTkyNzE3MjA4fQ.beGx_flz8NptY1oh0rO19d_fds8hsqWKPulEDpmUBS4
Content-Type: application/json

{
    "plate": "pizza 1",
    "price": 150.50
}


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "name": "kmery",
    "password": "test"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "name": "user",
    "password": "test"
}

###
GET http://localhost:5000/users
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTU5MDI3Mjg0NywiZXhwIjoxNTkwMjc2NDQ3fQ.fA7gjP2cnts_4-rnDHbVbNbyQ0aw3KUgDqT5DF9HJNA
Content-Type: application/json